# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 871a6671b97dc313851bde3efb4500bdfbf413b190ecac633198e3999b94b84f60c93ab942099e38d338e3914dd6bf8cce358568330a0a58e2d46d7c743c500a

test:
  secret_key_base: 0c5647877b0d1eccb12e5c6a522bad946842c4873062ccf2e0e2d6f2014ec69ea02751b6aa239c772c5c6d183922e9fc7224aa3c038a04bdf7da064cd7a904f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
